### ISSUE TITLE
Decide on JavaScript API

### ISSUE THREAD

**Issue by macdonst** [phonegap/phonegap-plugin-contentsync#1]
Decide on our API before we go about implementing the native side.

**Comment by mwbrooks** [comment]
Alright guys, @timkim and I have completed the JavaScript interface along with a test suite. We'd appreciate a review of whether the interface will satisfy your project's needs. Once we're in agreement, then we can dive into the native implementations.

Full API details on the [README.md](https://github.com/phonegap/phonegap-plugin-contentsync/blob/master/README.md).

Example:

```javascript
var sync = ContentSync.sync({ src: 'http://myserver' });

sync.on('progress', function(data) {
    // data.progress - Integer value representing progress precentage
});

sync.on('complete', function(data) {
    // data.localPath - browser-compatible path to the sync'd content
});

sync.on('error', function(e) {
    // e - Error object that describes the error
});

sync.on('cancel', function() {
    // trigged if event is cancelled
});

// can cancel the sync at any point
sync.cancel();
```

**Comment by arumsey** [comment]
Hi all,

The API is looking good but I have a few questions that are related to PGE's potential usage.

Where does the zip get synced and unzipped to? Can this be configured?
Can multiple archives be downloaded and independently unzipped later?
Will the API support server authentication?

**Comment by mwbrooks** [comment]
@arumsey thanks for the input!

> Where does the zip get synced and unzipped to? Can this be configured?

At the moment, we're allowing the native plugin to determine where the content is stored. I think a natural choice would be the SHA-1 hash of the src URL. However, if you have think this has issues, then we could allow the user to specify a destination path. If we provide a path, then it should be a relative path that the plugin can append to its chosen storage directory.

> Can multiple archives be downloaded and independently unzipped later?

No, at the moment, the download and unzip operations are both handled by `.sync` and abstracted by the native implementation. On completion, the `localPath` is returned, which the app can decide what to do with it. For example, add the sync'd app to a list of available apps or immediately change the browser's location to the new app path.

Do you have a need to download content immediately, but hold off on unzipping it until a later date?

> Will the API support server authentication?

Not at the moment, but it can. What kind of auth do you need to support?

**Comment by arumsey** [comment]
Hi @mwbrooks 

OK - Before the CS plugin was defined I was planning to add the ability to download multiple zips and then unzip one at a time when the user selected an app to view.  Since the CS plugin will sync and unzip as one operation being able to provide a relative path should solve the issue.  For each app requested the PGE app could pass a relative path to the CS plugin and then just maintain a list of available apps from the absolute paths returned by the sync operation.

eg.
```javascript
var sync = ContentSync.sync({ src: 'http://myserver', dest: 'app1', headers: {
                                "Authorization": "Basic <base64-encoded-auth>"  }   });
```

Will the localPath that is returned be able to pass that to `window.resolveLocalFileSystemURL` in order to get a FileEntry for when we want to delete an app?

The PGE viewing currently uses basic auth with AEM. An authorization header is passed to the FileDownload plugin right now for obtaining zips.

**Comment by timkim** [comment]
> Will the localPath that is returned be able to pass that to window.resolveLocalFileSystemURL in order to get a FileEntry for when we want to delete an app?

Should be able to. However, we're trying to write the plugin so it doesn't depend on any other plugin such as File. I think we'll be ok without having the dependency. 

I figure we'll save the file in a known file uri  on the native side (eg, https://github.com/apache/cordova-plugin-file/blob/master/doc/index.md#where-to-store-files). It also abstracts away from having to do a per-platform check on the js side for where the file should be. I know I ran into a lot of headaches trying to figure out how to save stuff on all the platforms (eg, https://github.com/phonegap/phonegap-app-developer/blob/content-sync-js/www/js/deploy.js#L153). 

> Not at the moment, but it can. What kind of auth do you need to support?

> The PGE viewing currently uses basic auth with AEM. An authorization header is passed to the FileDownload plugin right now for obtaining zips.
We'll have to add a `header` object like your example above.

**Comment by arumsey** [comment]
> Should be able to. However, we're trying to write the plugin so it doesn't depend on any other plugin such as File. I think we'll be ok without having the dependency. 

The plugin doesn't need to have a dependency on File but I just want to make sure there will be a way to remove what the CS plugin puts on the device if I wanted to.

**Comment by mwbrooks** [comment]
Thanks @arumsey! Again, excellent feedback.

> OK - Before the CS plugin was defined I was planning to add the ability to download multiple zips and then unzip one at a time when the user selected an app to view. Since the CS plugin will sync and unzip as one operation being able to provide a relative path should solve the issue. For each app requested the PGE app could pass a relative path to the CS plugin and then just maintain a list of available apps from the absolute paths returned by the sync operation.

Yea, I think the current sync solution will solve your scenario. You can use contentsync to fetch and store each app, then store each app's File URI so that you can maintain a list of apps to run.

The general rule of `localPath` is that it should be a browser-compatible URI. Sometimes that means different things on different platforms. Regardless, you should be able to point a CordovaWebview or InAppBrowser to the returned URI and have it display the `index.html` of that path.

> The PGE viewing currently uses basic auth with AEM. An authorization header is passed to the FileDownload plugin right now for obtaining zips.
> ```
> var sync = ContentSync.sync({
>     src: 'http://myserver',
>     dest: 'app1',
>     headers: { "Authorization": "Basic <base64-encoded-auth>"  }
> });
> ```

Awesome suggestion. At the moment, we don't pass headers, but we should and we can. I'll add that as a new issue.

> `dest: 'app1'`

@arumsey I was hoping to avoid requiring a `dest` parameter? But we may have to...

Originally, I hoped that the ContentSync plugin could use a SHA-1 of the src URL to generate a unique ID. On future sync's, it can lookup by once again taking the SHA-1 of the src URL.

However, thinking about it more, this will not work for URLs that use query string parameters. Depending on the server, the query string may be required to specify the content to sync. It may also have a variable value, such as a timestamp, to retrieve the delta updates. So for that reason, we would need to provide our own `dest` value.

I'll create another issue to track this change. We can talk more about it there.
